grafana.ini:
  default:
    instance_name: grafana.o11y.party
  auth.basic:
    enabled: true
  security:
    allow_embedding: true
    cookie_samesite: lax
  feature_toggles:
    publicDashboards: true
